apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: agrosolutions-propriedades
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agrosolutions-propriedades
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
